# プロジェクト関連配置
ebs:
  # 名称
  name: EBS rfid demo
  # バージョン
  version: 1.0.0
  # 著作権年
  copyrightYear: 2024
  # インスタンスデモスイッチ
  demoEnabled: false
  # ファイルパス 例（ Windows配置D:/ebs/uploadPath，Linux配置 /home/ebs/uploadPath）
  profile: D:/ebs/uploadPath
  # ipアドレスの取得スイッチ
  addressEnabled: false

# 開発環境配置
server:
  # サーバのHTTPポート、デフォルトは80
  port: 80
  servlet:
    # アクセスパス
    context-path: /
  tomcat:
    # tomcatのURIエンコード
    uri-encoding: UTF-8
    # 接続数がいっぱいになった後のキュー数、デフォルトは100
    accept-count: 1000
    threads:
      # tomcatスレッドの最大数、デフォルトは200
      max: 800
      # Tomcat初期化を開始したスレッド数、デフォルトは10
      min-spare: 100
 
# ログ配置
logging:
  level:
    com.ebs: debug
    org.springframework: warn

# 用户配置
user:
  password:
    # パスワード不正{maxRetryCount}回、10分間をロック
    maxRetryCount: 5

# Spring配置
spring:
  # テンプレートエンジン
  thymeleaf:
    mode: HTML
    encoding: utf-8
    # キャッシュを無効にする
    cache: false
  # リソース情報
  messages:
    # 国際化リソースファイルパス
    basename: static/i18n/messages
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  profiles:
    active: druid
  # ファイルアップロード
  servlet:
    multipart:
      # 単一ファイルサイズ
      max-file-size: 10MB
      # アップロードされたファイルの合計サイズ
      max-request-size: 20MB
  # サービスモジュール
  devtools:
    restart:
      # ホットデプロイスイッチ
      enabled: true

# MyBatis
mybatis:
  # 指定されたパッケージ別名の検索
  typeAliasesPackage: com.ebs.**.domain
  # 全部mapper.xml映射文件マップファイルを見つかり
  mapperLocations: classpath*:mapper/**/*Mapper.xml
  # グローバルなプロファイルのロード
  configLocation: classpath:mybatis/mybatis-config.xml

# PageHelperページングプラグイン
pagehelper:
  helperDialect: mysql
  supportMethodsArguments: true
  params: count=countSql

# Shiro
shiro:
  user:
    # ログインアドレス
    loginUrl: /login
    # 権限認証失敗アドレス
    unauthorizedUrl: /unauth
    # ホームアドレス
    indexUrl: /index
    # 認証コードスイッチ
    captchaEnabled: false
    # 認証コードタイプ math ディジタル計算 char 文字認証
    captchaType: math
  cookie:
    # Cookieのドメイン デフォルトは空、現在アクセスしているドメイン名
    domain:
    # cookieの有効なアクセスパス
    path: /
    # HttpOnly属性
    httpOnly: true
    # Cookieの有効期限、日単位
    maxAge: 30
    # キー、一意性を維持する必要があります
    cipherKey:
  session:
    # Sessionタイムアウト時間、-1が期限切れにならないことを表す（デフォルト30分）
    expireTime: 30
    # データベースへのセッションの同期化のサイクル（デフォルト1分）
    dbSyncPeriod: 1
    # sessionチェック時間、デフォルト10分
    validationInterval: 10
    # 同じユーザーの最大セッション数、デフォルト-1：制限なし）
    maxSession: -1
    # 
    kickoutAfter: false
  rememberMe:
    # パスワードを保存するか
    enabled: true

# XSS攻撃を防ぐ
xss:
  # フィルタスイッチ
  enabled: true
  # リンクを除外（複数の場合、カンマで区切り）
  excludes: /system/notice/*
  # 一致リンク
  urlPatterns: /system/*,/monitor/*,/tool/*

# Swagger配置
swagger:
  # swaggerがオンにするかどうか
  enabled: true

redis:
  host: localhost
  port: 6379
  password: 123456
